### ISSUE TITLE
当前日期之前的不能点击可以实现吗

### ISSUE THREAD

**Issue by zaaach** [TUBB/CalendarSelector#3]

**Comment by TUBB** [comment]
可以，如果你使用了SingleMonthSelector或CalendarSelector是支持点击事件拦截的

**Comment by TUBB** [comment]
分别对应IntervalSelectListener和SegmentSelectListener

**Comment by TUBB** [comment]
如果没有使用这两者，就需要自己判断日期了，稍微麻烦一点

**Comment by zaaach** [comment]
恩好，我研究下
