### ISSUE TITLE
你好，CalendarSelector 模式下 如何动态设置 默认选择日期

### ISSUE THREAD

**Issue by haoyunpeng1994** [TUBB/CalendarSelector#4]
需求是 当我 设定一个范围后 比如 2016年1月-12月，进入日期选择界面后 自动跳转到当天日期 
比如:2016年 6月7日 ，并且日期为选中状态，然后通过点击把数据返回上一activity(点击默认选中的日期直接返回，点击其他的把选中状态更换再返回数据) 类似于携程的日期选择
跳转用scrollToPosition可以办到，然后默认选择日期 我看源码发现可以通过
 for (SCMonth scMonth : data) {
            if (scMonth.getYear() == 2016 && scMonth.getMonth() == 6) {
                FullDay fullDay = new FullDay(2016,6,7);
                scMonth.addSelectedDay(fullDay);
            }
        }
实现，但是要想单选切换选中状态还是很麻烦的，还不知道怎么移除上一个选中日期

**Comment by TUBB** [comment]
不好意思，CalendarSelector模式下暂时还不支持设置默认选取的日期。
可以说说你的需求吗，可以的话，晚上帮你加上~

**Comment by haoyunpeng1994** [comment]
感谢你的代码。

**Comment by TUBB** [comment]
你上面的做法解决不了你的问题的，因为CalendarSelector内部有些状态要进行设置，而且还要区分不同的Mode，我晚上帮你看看吧。这种需求确实挺常见的，下个版本会加上 ：）

**Comment by haoyunpeng1994** [comment]
刚才我已经达到了我的需求，最后刷新问题也解决了，我只在关心的那个mode里面 case INTERVAL:做了修改，但肯定整体代码的把握比不上你写的，如果您更新了，我也会更新的。

**Comment by TUBB** [comment]
其实完全可以自己自定义一个Selector  😄

**Comment by TUBB** [comment]
我在default-selected-days分支上把这个功能加上了，可以帮忙试试符合你的需求吗？

**Comment by manburenshenglu** [comment]
LZ，我也遇到了这个需求，default-selected-days分支上如何清空不同月份的选中状态？
